version: '3.8'
services:
  app:
    build: .
    container_name: aviso_vencimentos
    command: python aviso_vencimentos.py
    # volumes removido para evitar sobrescrever arquivos do container
    working_dir: /app
